### ISSUE TITLE
Completing open source implementation

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/openaq-engine#47]
- [x] MUST have a OSI-approved license distributed with public source code repositories by end of Q2.
- [x] Create contributing guidelines for all Open Source repositories. Explain how someone makes a contribution to the projects. Add to documentation website created in previous quarter.
- [x] Create public tickets/issues that correspond to planned features and known bugs/problems with Open Source repositories.
- [x] Establish an Open Source quality assurance process. 
- [x] Explore unit testing frameworks for front-end/back-end software, if applicable. Document user stories and test cases for games, if applicable. Document data structures and algorithm decisions for data science, if applicable.
Add either developer or user documentation to the Open Source documentation site. (Hint: Developer docs often include API docs, architecture or system state diagrams, or deployment guides.)
- [x] Identify a Code of Conduct for any public Open Source repositories. Upload it to public source code repositories. Create internal documentation for how to respond to a Code of Conduct report, if one were to be made.

**Comment by jit-1** [comment]
- [x] OSI Approved License Distribution: https://github.com/AQ-AI/openaq-engine/blob/master/license
- [x] Create contributing guidelines for all Open Source repositories:  https://github.com/AQ-AI/openaq-engine/blob/master/.github/CONTRIBUTING.md
- [x] Create public tickets/issues: https://github.com/AQ-AI/openaq-engine/issues
- [x] Code of Conduct for Public Open Source Repositories: openaq-engine: https://github.com/AQ-AI/openaq-engine/blob/master/.github/CODE_OF_CONDUCT.md
