### ISSUE TITLE
Sphinx Installation Error

### ISSUE THREAD

**Issue by jit-1** [AQ-AI/openaq-engine#56]
Python: 3.10.4
`>>poetry add sphinx`
`sphinx (>=6.1.3,<7.0.0) is incompatible with awscli (>=1.27.2,<2.0.0). So, because openaq-engine depends on both awscli (^1.27.2) and Sphinx (^6.1.3), version solving failed.`

**Comment by ChristinaLast** [comment]
Connected to Python issue: 3.9.4 (this could be connected).

**Comment by ChristinaLast** [comment]
Added changes on branch:
- removing `.python-version` 
rerun:

```
poetry install
```
