### ISSUE TITLE
Integrate you publish the Airflow structure in https://github.com/Ali-Maq/aqi to https://github.com/AQ-AI/openaq-engine

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/openaq-engine#60]
The structure of the airflow is quite different from the `openaq-pipeline`
From what I can see the following:

### [processing](https://github.com/Ali-Maq/aqi/tree/master/src/processing/)

1.   [buffer_processor.py](https://github.com/Ali-Maq/aqi/blob/master/src/processing/buffer_processor.py) 
- this doesnt need to exist if we are handling through earth engine (the resolution of the image is the buffer by default)
3. [feature_extractor.py](https://github.com/Ali-Maq/aqi/blob/master/src/processing/feature_extractor.py)
- I am assuming this is where we do the satellites
5. [feature_merger.py](https://github.com/Ali-Maq/aqi/blob/master/src/processing/feature_merger.py) 
- is this where we combine the field data from the satellites (e.g. with regardstot he lookback used)?
7. [vrt_creator.py](https://github.com/Ali-Maq/aqi/blob/master/src/processing/vrt_creator.py)
- We are not using vrt at the moment. But this is an option for when we only query from our local data store.

### [authentication](https://github.com/Ali-Maq/aqi/tree/master/src/authentication/)
1. [openaq_auth.py](https://github.com/Ali-Maq/aqi/blob/master/src/authentication/openaq_auth.py)
- when in airflow will these happen?  
3. [earth_engine_auth.py](https://github.com/Ali-Maq/aqi/blob/master/src/authentication/earth_engine_auth.py)
- this authentication might need to happen for every earth engine query. so the two auth processes my be executed at different times in the pipeline.

### [extraction](https://github.com/Ali-Maq/aqi/tree/master/src/extraction)
1. [gadm_extractor.py](https://github.com/Ali-Maq/aqi/blob/master/src/extraction/gadm_extractor.py)
- At the moment we arent using city-masks to extract features, although this is a possibility (combining with local file storage and vrt)
3. [geo_location_generator.py](https://github.com/Ali-Maq/aqi/blob/master/src/extraction/geo_location_generator.py)
- not sure what this does? is this generation for the prediction locations? In the first version the random points we used just for model testing, in the deployed models, we will need to sample from a grid of the agreed-upon spatial resolution.
4. [openaq_extractor.py](https://github.com/Ali-Maq/aqi/blob/master/src/extraction/openaq_extractor.py)
- is this time splitter +cohort filter + cohort builder?

**Comment by Ali-Maq** [comment]
TASK for today September 19 2023 

##Processing : 

1. Buffer processing - If this is happening on the google earth engine, Then I am removing this 
3. Yes this is where we do the the ee_data.py thing to get the satellite data 
5. regards to????  I don't get this, Yes this is where we get the satellite data and I am using the image collection method both in parallel and series in th existing pipeline 
7. I will remove this and change the workflow.
 
*- Working on Google credentials generation and will share it with you @ChristinaLast , Should I just push the changes in the config file?

- Can I see what is the mlflow error , so I can run and try to fix it
