### ISSUE TITLE
Add Model Card to repo

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/openaq-engine#70]
- [Something similar to ](https://huggingface.co/docs/hub/model-cards)Model
 Cards.

**Comment by jit-1** [comment]
Recommended Modifications for Model_Card.md:

1. Removing the word [optional] at Line Numbers:

- [x]  27
- [x] 28
- [x] 32
- [x] 39
- [x] 40
- [x] 52
- [x] 95
- [x] 103
- [x] 141
- [x] 159

2. Adding details of the Metrics Section [starting Line 127] & making the necessary changes to Results Section [ Starting Line 133]. The result section needs further evaluation.
- [x] Changes Made

3. Environmental Impact [Line 147]
- [x] Need to Add details

4. Hardware Details [Line 169]
- [x] Add AWS Instance Details (Instance Type, RAM, SDD, vCPUs)

5. Software Details [Line 173]
- [x] Add Software Library Used [OpenMP (lightgbm), xgboost, etc]

**Comment by ChristinaLast** [comment]
Added changes in #71
